### ISSUE TITLE
Add ability to go short

### ISSUE THREAD

**Issue by nkhoit** [lhillmer/OttoBot#9]
Add the commands: `$broker sellshort <quantity>` and `$broker buyshort <quantity>`
`$broker sellshort` will allow you to borrow shares from OttoBot and sell it immediately, going short on the stock. This will immediately grant you cash at the current price and give you a negative quantity of the corresponding stock.

`$broker buyshort` will allow you to buy a stock you are short on to give back to OttoBot. This will deduct cash of the stock's current value and add the stock's quantity back to your balance.

You should only be able to go short on as much as your total assets. If you have $1000 total worth of cash and stock, you will be able to go short on $1000 worth of stock. ie. you will only be allowed to have a maximum ratio of assets to liabilities of 2:1.

The percent change of your investment will be based on the value you took the loan at. 
percent change = (1 - value of underlying asset / cost basis of the short position) * 100. 
So if you took a short position worth $1000 and the value of the underlying asset goes to $0, you'll be +100%. It follows that for the same trade, if the underlying asset goes to $2000, you'll be -100%. 

This should show up as a 'liability' on the balance sheet. So your total value will be your Assets (cash+stock value) - Liabilities (short value). 

If the value of your liabilities go above your assets, your balance will become negative. In this situation, the brokerage will only allow you to sell stocks or buy back shorts. You will have to deposit more Momocoins or have your assets increase in value in order to continue to buy stock or sell shorts.

**Comment by lhillmer** [comment]
This issue has been moved to the new repo, OttoBroker.
